CREATE DATABASE IF NOT EXISTS yeticave
    DEFAULT CHARACTER SET utf8
    DEFAULT COLLATE utf8_general_ci;

USE yeticave;

CREATE TABLE IF NOT EXISTS categories (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(128) NOT NULL UNIQUE,
    code VARCHAR(128) NOT NULL
);

CREATE TABLE IF NOT EXISTS lots (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    add_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    description TEXT NOT NULL,
    image_link VARCHAR (255),
    start_price DECIMAL (10, 2) UNSIGNED NOT NULL,
    expiration_date TIMESTAMP NOT NULL,
    step_sum DECIMAL (10, 2) UNSIGNED NOT NULL,
    author_id INT NOT NULL,
    winner_id INT NOT NULL,
    category_id INT NOT NULL
);

CREATE TABLE IF NOT EXISTS bet (
    id INT AUTO_INCREMENT PRIMARY KEY,
    bet_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    sum_price DECIMAL (10, 2) UNSIGNED NOT NULL,
    user_id INT NOT NULL,
    lot_id  INT NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    email VARCHAR(128) NOT NULL UNIQUE,
    name VARCHAR(128) NOT NULL,
    password VARCHAR(64) NOT NULL,
    contact_inf TEXT NOT NULL
);

